[project]
name = "ariabot"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "fastapi>=0.141.1",
    "gradio>=6.24.0",
    "httpx>=0.28.1",
    "langchain-core>=1.5.4",
    "langgraph>=1.2.11",
    "python-dotenv>=1.2.2",
    "redis>=8.1.0",
    "uvicorn[standard]>=0.52.2",
]
